# Generated by Django 5.2.16 on 2026-08-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='分类标识')),
                ('description', models.TextField(blank=True, default='', verbose_name='分类说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '问题分类',
                'verbose_name_plural': '问题分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='搜索关键词')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='结果数量')),
                ('has_result', models.BooleanField(default=False, verbose_name='是否有结果')),
                ('session_key', models.CharField(blank=True, default='', max_length=100, verbose_name='Session标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('clicked_result', models.BooleanField(default=False, verbose_name='是否点击结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
            ],
            options={
                'verbose_name': '搜索记录',
                'verbose_name_plural': '搜索记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题内容')),
                ('description', models.TextField(blank=True, default='', verbose_name='补充说明')),
                ('session_key', models.CharField(blank=True, default='', max_length=100, verbose_name='Session标识')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('answered', '已补充答案'), ('ignored', '暂不处理')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '未解决问题',
                'verbose_name_plural': '未解决问题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='问题标题')),
                ('short_answer', models.TextField(verbose_name='简短答案')),
                ('detailed_answer', models.TextField(blank=True, default='', verbose_name='详细答案')),
                ('keywords', models.CharField(blank=True, default='', help_text='多个关键词用逗号分隔', max_length=300, verbose_name='关键词')),
                ('information_type', models.CharField(choices=[('official', '学校官方信息'), ('curated', '管理员整理'), ('experience', '学长学姐经验'), ('reference', '普通参考信息')], default='curated', max_length=20, verbose_name='信息类型')),
                ('source_name', models.CharField(blank=True, default='', max_length=200, verbose_name='来源名称')),
                ('source_url', models.URLField(blank=True, default='', verbose_name='来源链接')),
                ('applicable_audience', models.CharField(blank=True, default='', max_length=200, verbose_name='适用对象')),
                ('verified_at', models.DateField(blank=True, null=True, verbose_name='最后核验时间')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='有帮助数量')),
                ('unhelpful_count', models.PositiveIntegerField(default=0, verbose_name='没有帮助数量')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='knowledge.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '知识条目',
                'verbose_name_plural': '知识条目',
                'ordering': ['-is_featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(verbose_name='是否有帮助')),
                ('comment', models.TextField(blank=True, default='', verbose_name='补充意见')),
                ('session_key', models.CharField(blank=True, default='', max_length=100, verbose_name='Session标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='knowledge.knowledgeitem', verbose_name='对应问题')),
            ],
            options={
                'verbose_name': '内容反馈',
                'verbose_name_plural': '内容反馈',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['title'], name='knowledge_k_title_7a37e9_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['category'], name='knowledge_k_categor_16529c_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['is_published'], name='knowledge_k_is_publ_d501a9_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['is_featured'], name='knowledge_k_is_feat_9a8bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeitem',
            index=models.Index(fields=['updated_at'], name='knowledge_k_updated_988cad_idx'),
        ),
    ]
